name: 'PR Analyzer'
description: 'Analyze pull requests using AI to provide code review insights'
author: 'Your Team'
branding:
  icon: 'zap'
  color: 'blue'

inputs:
  config-path:
    description: 'Path to the configuration file'
    required: false
    default: '.pr-analyzer.yml'

runs:
  using: 'node20'
  main: 'dist/index.js'